name: Create jira issue from github issue

on:
  issues:
    types: [closed]
jobs:
  create_jira_task:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Find in commit messages
      id: find 
      uses: atlassian/gajira-find-issue-key@master
      with:
        string: ${{ github.event.ref }}
    - name: Find issue info
      run: echo "Issue ${{steps.find.outputs.issue }} was found"