name: Create jira issue from github issue

on:
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        value: ${{ github.actor }}
        required: true
        type: string

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}