name: Create jira issue from github issue

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const githubId = ${{github.actor}}
            const accountId = process.env.githubId
            echo accountId
            console.log('result: ',accountId)