name: Create jira issue from github issue

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const githubId = context.payload.issue.assignee.login
            const accountId = {githubId} = process.env
            console.log(accountId)